spring:
    application:
      name: intelligent-learning-system-management
    #mysql连接配置
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/learn
      username: root
      password: 1234

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  helper-dialect: mysql

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aws:
  s3:
    endpoint: https://s3.eu-central-1.amazonaws.com
    bucketName: learncontroller
    region: eu-central-1

